In [ ]:
## Test for RadDINO

In [2]:
import pandas as pd
import numpy as np
from mammo_prep import artifacts,io,normalize,viz,windowing
from pathlib import Path

In [3]:
# ROUTES

ANNOTATIONS_CSV = Path(
"/home/enric/Datasets/Original/vindr/finding_annotations.csv"
)

In [23]:
# Import dataset

df =pd.read_csv(ANNOTATIONS_CSV)

df.head(5)
df["healthy"]=["no_lesion" if x == "['No Finding']" else "has_lesion" for x in df["finding_categories"]]


df.head(5)

freq = pd.crosstab(df["healthy"],df["split"])
freq

split       test  training
healthy
has_lesion   452      1802
no_lesion   3643     14589

In [24]:
percentage = freq.div(freq.sum(axis=1), axis=0)
percentage

split           test  training
healthy
has_lesion  0.200532  0.799468
no_lesion   0.199814  0.800186

In [ ]:
from PIL import Image
from torchvision import transforms
import timm, torch
import pydicom

data_dicom = pydicom.dcmread("/home/enric/Datasets/Original/vindr/images/5a286b78f7e0e3cfe6c861e23a9fa8c3/32a6cb78f0e4a0bdd95c56c4cb6ac673.dicom")
pixels = data_dicom.pixel_array.astype(float)
pixels_rescaling = (pixels-np.min(pixels))/(np.max(pixels)-np.min(pixels))*255.0
image_8bit = np.uint8(pixels_rescaling)

pil_image = Image.fromarray(image_8bit).convert("RGB")

# Load pretrained model from Hugging Face Hub
model = timm.create_model("hf_hub:Snarcy/RadioDino-s16", pretrained=True)
model.eval().to("cuda" if torch.cuda.is_available() else "cpu")

# Prepare image
image = pil_image
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225]),
])
input_tensor = transform(image).unsqueeze(0).to("cuda" if torch.cuda.is_available() else "cpu")

# Extract features
with torch.no_grad():
    embedding = model(input_tensor)

KeyboardInterrupt:

In [7]:
embedding

tensor([[-1.7960e+00,  1.5148e-01,  1.5923e-01, -9.7486e-01, -4.3515e-01,
          9.7774e-01, -1.9227e-01,  2.2123e-02,  6.5971e-01,  1.7615e+00,
          1.3768e+00, -8.1276e-01, -2.5027e+00, -8.8963e-01,  2.1723e-01,
          5.4267e-01, -1.1421e-02, -5.2607e-01, -1.9109e+00, -9.6790e-01,
          5.8625e-02, -6.0632e-01, -3.5641e-01,  1.3698e+00, -1.4118e-01,
          1.2773e+00, -1.8319e+00, -1.4355e-01, -4.4146e-01, -3.9980e-01,
          2.0936e+00,  3.1946e-01,  1.0536e+00,  1.2460e+00, -1.5803e+00,
          1.0260e+00, -2.0063e-01, -1.1621e+00, -1.6088e-01, -3.3426e-01,
          7.5673e-02,  1.7306e+00,  7.6373e-01, -2.1101e-01, -3.6847e-01,
          1.0891e+00, -5.1715e-01, -2.9272e-01,  7.5577e-01, -6.4187e-01,
          4.7161e-01,  5.2764e-01,  5.9118e-01,  1.2603e-01, -5.4806e+00,
          2.1030e+00, -5.5163e-01, -5.1547e-02, -7.7596e-01, -5.4223e-01,
          6.0643e-01, -5.0241e-01,  5.5342e-01, -8.1139e-01,  2.2908e-01,
          4.5721e-01, -9.1576e-01,  1.5555e+00, -7.9120e-02,  1.1407e+00,
          1.8105e-01,  1.3303e+00, -1.9098e+00, -4.5135e-02, -4.7929e-01,
          2.3169e-01, -5.4141e-01, -6.7706e-01,  5.1107e-01, -3.1809e-01,
         -1.8482e-01, -4.5128e-02,  2.8002e+00, -6.8499e-01, -3.4232e+00,
          1.2582e+00,  1.7772e+00, -6.3662e-01,  6.3382e-02, -5.2477e-01,
         -2.8288e-01, -8.7274e-01, -7.3024e-01,  1.6006e+00, -9.2778e-01,
         -6.6790e-01,  5.6975e-01, -5.3683e-01, -1.6010e-02,  5.9841e-01,
          9.0493e-01, -8.9332e-01, -6.7689e-01, -8.6584e-01,  2.7090e-01,
          1.4183e+00, -5.4284e-01,  1.3808e+00,  9.8682e-03,  7.9226e-02,
         -5.9314e-01, -5.0094e-01, -3.6232e-01,  2.0528e+00, -1.0040e+00,
         -2.0326e-01, -1.7135e+00, -5.4846e-02,  1.3908e+00,  5.7396e-01,
          4.4350e-02,  3.7686e-01,  9.7674e-01, -1.0534e+00, -6.8417e-01,
          1.5313e-01,  8.9870e-01,  6.0040e-01, -2.6979e-01,  1.2076e+00,
          1.1440e+00,  1.9010e+00,  4.7311e-01,  4.2396e-01, -9.5314e-01,
         -4.0945e-01,  4.9091e-01,  2.9360e-01,  2.0170e-01,  1.1782e+00,
          1.4393e+00, -7.2144e-01,  1.1893e+00, -4.4989e-01,  1.4951e+00,
         -1.5634e+00, -3.7683e-02, -1.6355e+00, -3.9502e-01,  1.4555e+00,
         -4.1696e-01, -6.6772e-01,  1.1028e-03,  4.7415e-01,  5.8741e-01,
         -1.6798e+00,  1.0649e+00,  8.0107e-01,  4.9054e-01, -6.2219e-01,
         -4.9003e-01, -4.7638e-01,  2.0897e-01, -2.9283e-01,  1.1394e+00,
          4.8941e-01,  5.0775e-01, -7.9075e-01, -5.0930e-01, -5.0573e-01,
          2.4345e-01,  4.1479e-01, -1.3806e+00, -4.1862e-02, -9.9310e-01,
          9.9042e-01, -4.9324e-01, -1.1217e+00,  4.7001e-01,  6.5531e-01,
          1.3711e-03, -1.0522e+00,  9.1646e-01, -2.6052e+00, -1.4314e+00,
         -1.3374e+00,  3.8765e-01,  1.0865e-01, -7.0628e-01,  2.2408e-01,
         -1.1354e+00, -4.3653e-01, -9.7200e-01,  9.7230e-01, -3.8695e-01,
         -7.9601e-01, -7.1064e-01,  1.1617e+00,  1.0599e-01,  5.1023e-01,
         -8.6062e-01,  7.0367e-01, -1.5606e+00, -1.8465e-01, -3.7107e-01,
         -1.5350e-01,  2.1666e-01, -9.7140e-02,  4.8255e-01, -4.3761e-01,
         -1.3513e+00,  1.8952e+00, -5.1468e-01,  7.0907e-01, -1.7091e-02,
         -1.5635e-01,  8.7565e-01, -5.8988e-02,  6.7570e-01,  9.4998e-01,
         -1.1065e+00,  1.2444e+00,  5.6698e-01, -1.2584e-01,  2.3198e-02,
          5.4191e-01,  3.4314e-01, -6.4644e-02,  1.8436e-01,  6.2288e-01,
          5.1407e-02, -6.1564e-01,  4.1190e-01,  3.3118e-02,  1.3263e-01,
          5.9349e-01, -7.9580e-01, -1.0596e-01,  2.7996e-01, -1.7788e-01,
         -1.5427e+00,  3.7973e-01,  3.9253e-01, -8.3700e-01,  8.9533e-01,
         -9.8595e-01, -7.6063e-01,  5.2621e-01,  1.3758e+00, -9.8797e-01,
          1.9860e-01,  2.6240e-01,  2.3724e-01,  1.2960e+00, -2.8953e-01,
          2.6541e-01,  1.0924e+00, -1.8252e+00,  6.4217e-01,  1.0776e+00,
         -2.2143e-01, -6.1651e-01, -1.0576e+00, -4.9397e-02,  2.2432e+00,
          6.9422e-02,  4.8518e-01,  1.0678e+00,  8.7245e-02, -6.1838e-01,
         -2.0531e-01, -1.6934e-01,  6.3942e-01, -6.9502e-01, -2.2960e+00,
         -7.4959e-01,  4.6427e-01,  3.0964e-01,  3.1971e-01, -2.3564e-01,
         -1.8134e-01, -1.5586e-01,  1.3182e+00,  2.7865e-01,  1.4269e+00,
         -6.9525e-01,  8.5357e-01, -1.2744e+00, -1.1708e+00, -5.2224e-01,
         -9.9209e-01, -1.3015e+00, -1.0316e-02,  5.7232e-01,  6.4699e-01,
         -3.9163e-01, -9.8985e-01, -1.7848e-01,  1.3289e+00,  8.3903e-01,
         -1.1663e+00, -1.4043e+00, -7.6969e-01, -6.5588e-02, -1.7148e+00,
         -1.8438e+00,  2.9134e-01, -3.6677e-01, -8.7266e-01,  7.1849e-01,
         -1.0974e+00,  8.0898e-01, -9.6904e-01,  9.5889e-01, -4.9756e-01,
         -8.0954e-01, -3.3794e-01, -1.9479e-01,  3.6334e-01,  1.0142e+00,
          6.5775e-02,  6.4315e-01,  1.2801e+00, -8.9247e-01, -1.3276e+00,
         -8.6115e-01,  2.3263e+00,  1.8489e+00, -6.3858e-02, -1.5198e-01,
         -8.6881e-01,  1.3509e-01,  5.9122e-01,  1.1353e+00,  5.0536e-01,
          1.3691e+00, -5.2127e-01, -5.2516e-01, -3.2412e-02,  1.5409e-01,
         -2.0033e+00,  1.1330e+00,  2.0662e+00, -4.8232e-01, -4.3266e-01,
         -4.9705e-01, -1.0131e+00,  9.3692e-02, -3.2955e+00, -1.0184e+00,
         -9.5403e-01, -1.7599e-01,  3.9285e-02,  2.1115e+00, -5.9964e-01,
          1.4285e+00, -1.0043e+00, -5.2444e-01, -9.1375e-01,  2.2292e-02,
          1.4316e+00,  8.3661e-02, -5.0840e-01,  1.8604e-01, -3.7919e-01,
          7.0605e-02,  8.3964e-01,  9.1489e-01,  4.2991e-01,  5.0823e-01,
          2.0891e-01,  8.0209e-01,  1.4047e+00,  7.7879e-01, -2.0675e-01,
          1.2504e+00, -3.7971e-01, -1.0435e+00, -1.5296e-01, -1.1083e+00,
          2.0514e+00,  9.2519e-01, -3.1328e-01,  3.6265e-01]], device='cuda:0')